---
language: php

sudo: required

php:
  - 8.0

env:
  global:
    - XDEBUG_MODE=coverage

install:
  - composer install

jobs:
  include:
    - stage: "Standards"
      name: "php cs"
      script: vendor/bin/phpcs -s
    - script: php -dmemory_limit=-1 vendor/bin/phpstan analyse --level=max src/
      name: "php stan"
    - stage: "php unit"
      script: vendor/bin/phpunit --coverage-text --colors=never --log-junit var/unit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
